csv 파일 읽어오기

In [1]:
import pandas as pd
df = pd.read_csv('webLog.csv')
df

               IP                   Time                        URL  Staus
0      10.131.2.1  [30/Nov/2017:08:46:59             GET / HTTP/1.0    302
1      10.128.2.1  [29/Nov/2017:16:45:00             GET / HTTP/1.1    302
2      10.128.2.1  [29/Nov/2017:17:00:05             GET / HTTP/1.1    302
3      10.128.2.1  [29/Nov/2017:18:15:39             GET / HTTP/1.1    200
4      10.128.2.1  [29/Nov/2017:22:21:16             GET / HTTP/1.1    302
...           ...                    ...                        ...    ...
15784  10.128.2.1  [12/Nov/2017:12:58:39  POST /update.php HTTP/1.1    200
15785  10.129.2.1  [12/Nov/2017:12:43:54  POST /update.php HTTP/1.1    200
15786  10.129.2.1  [12/Nov/2017:12:43:54  POST /update.php HTTP/1.1    200
15787  10.131.0.1  [30/Nov/2017:15:57:41  POST /update.php HTTP/1.1    200
15788  10.131.0.1  [30/Nov/2017:17:16:26  POST /update.php HTTP/1.1    200

[15789 rows x 4 columns]

한 열씩 정렬

In [13]:
#시간 기준
df_sort_time = df.sort_values(by=df.columns[1], ascending=True)
print(df_sort_time)

#ip 기준
df_sort_ip = df.sort_values(by=df.columns[0], ascending=True)
print(df_sort_ip)

               IP                   Time  \
240    10.129.2.1  [01/Dec/2017:00:06:02
13984  10.131.2.1  [01/Dec/2017:00:06:02
376    10.130.2.1  [01/Dec/2017:00:40:11
10875  10.128.2.1  [01/Dec/2017:00:40:11
15679  10.131.0.1  [01/Dec/2017:00:41:00
...           ...                    ...
5490   10.129.2.1  [30/Nov/2017:21:01:34
10874  10.128.2.1  [30/Nov/2017:21:29:16
767    10.131.2.1  [30/Nov/2017:21:29:16
239    10.129.2.1  [30/Nov/2017:21:48:21
13983  10.131.2.1  [30/Nov/2017:21:48:22

                                                     URL  Staus
240                                       GET / HTTP/1.1    302
13984                            GET /login.php HTTP/1.1    200
376                                       GET / HTTP/1.1    302
10875                            GET /login.php HTTP/1.1    200
15679                         POST /process.php HTTP/1.1    302
...                                                  ...    ...
5490   GET /details.php?name=Factorial%20Factorizatio...    200
10874                            GET /login.php HTTP/1.1    200
767                                       GET / HTTP/1.1    302
239                                       GET / HTTP/1.1    302
13983                            GET /login.php HTTP/1.1    200

[15789 rows x 4 columns]
               IP                   Time                                  URL  \
11377  10.128.2.1  [29/Jan/2018:20:36:44              GET /login.php HTTP/1.1
3155   10.128.2.1  [14/Dec/2017:10:15:53  GET /css/bootstrap.min.css HTTP/1.1
3156   10.128.2.1  [15/Dec/2017:08:47:56  GET /css/bootstrap.min.css HTTP/1.1
3157   10.128.2.1  [15/Dec/2017:17:06:49  GET /css/bootstrap.min.css HTTP/1.1
3158   10.128.2.1  [16/Dec/2017:00:48:42  GET /css/bootstrap.min.css HTTP/1.1
...           ...                    ...                                  ...
14240  10.131.2.1  [01/Dec/2017:18:11:38   GET /login.php?value=fail HTTP/1.1
14239  10.131.2.1  [30/Nov/2017:16:06:28   GET /login.php?value=fail HTTP/1.1
14238  10.131.2.1  [30/Nov/2017:15:45:20   GET /login.php?value=fail HTTP/1.1
8715   10.131.2.1  [30/Nov/2017:17:31:00           GET /img/ruet.png HTTP/1.1
0      10.131.2.1  [30/Nov/2017:08:46:59                       GET / HTTP/1.0

       Staus
11377    200
3155     304
3156     200
3157     304
3158     200
...      ...
14240    200
14239    200
14238    200
8715     200
0        302

[15789 rows x 4 columns]